---
- name: execute_gradle
  become_user: hybris
  remote_src: yes
  shell: |
    cd {{ installation_folder }}
    ./gradlew setup

- name: change_permissions
  become_user: root
  file:
    path: "{{ installation_folder }}"
    owner: hybris
    group: hybris
    recurse: yes
    mode: 0774

- name: execute_ant
  become_user: hybris
  remote_src: yes
  shell: |
    cd {{ installation_folder }}
    ./gradlew rebuild

- name: change_permissions
  become_user: root
  file:
    path: "{{ installation_folder }}"
    owner: hybris
    group: hybris
    recurse: yes
    mode: 0774

- name: change_local.properties
  become_user: hybris
  lineinfile:
    path: "{{ installation_folder }}/hybris/config/local.properties"
    regexp: "^db.url*"
    line: "db.url=jdbc:mysql://{{ mysql_host }}:{{ mysql_port }}/{{ db_name }}?useConfigs=maxPerformance&characterEncoding=utf8"

- name: initialize_hybris
  become_user: hybris
  shell: ./gradlew initialize
  args:
    chdir: "{{ installation_folder }}"
#  when: initialize
  register: init

- name: debug
  debug: var=init

- name: change_permissions
  become_user: root
  file:
    path: "{{ installation_folder }}"
    owner: hybris
    group: hybris
    recurse: yes
    mode: 0774

- name: hybris_script
  become_user: hybris
  template:
    src: "systemd.j2"
    dest: "{{ installation_folder }}/hybris/bin/platform/hybrisserver.sh"
    owner: hybris
    group: hybris
    mode: 0774

- name: start_hybris
  become_user: hybris
  command: /bin/sh {{ installation_folder }}/hybris/bin/platform/hybrisserver.sh start
  args:
   chdir: "{{ installation_folder }}/hybris/bin/platform/"





