---
- name: Create_the_database
  mysql_db:
    name="{{ item.name }}"
    state=present
    login_host="{{ mysql_host }}"
    login_password="{{ mysql_pass }}"
    login_user="{{ mysql_user }}"
    login_port="{{ mysql_port }}"
  with_items: "{{ mysql_db_datahub }}"


- name: Create the database users
  mysql_user:
    state=present
    login_host="{{ mysql_host }}"
    login_password="{{ mysql_pass }}"
    login_user="{{ mysql_user }}"
    login_port="{{ mysql_port }}"
    name="{{ item.name }}"
    password="{{ item.pass }}"
    priv="{{ item.priv }}"
  with_items: "{{ mysql_users_datahub }}"
  tags: datahub

